const fs = require("fs");
const file = __dirname + "/../extension/sidepanel/panel.js";
let lines = fs.readFileSync(file, "utf-8").split("\n");

// Replace lines 71-99 (0-indexed: 70-98) with clean code
const replacement = [
  '  try {',
  '    const pageInfo = await getCurrentTabInfo();',
  '    const systemPrompt = `你是一个浏览器助手。先用 explore 了解页面有哪些元素。',
  '',
  '步骤:',
  '1. 先发 <TOOL>explore</TOOL> 查看页面上有什么',
  '2. 根据探索结果用精确保选器操作',
  '3. 完成后回复 ✅ 完成',
  '',
  '示例:',
  '<TOOL>explore</TOOL>',
  '<TOOL>fill|#search|关键词</TOOL>',
  '<TOOL>pressKey|Enter</TOOL>',
  '<TOOL>wait|2000</TOOL>',
  '<TOOL>extract</TOOL>',
  '',
  "当前页面: ${pageInfo.url}`;",
  '',
  '    const messages = [',
  '      { role: "system", content: systemPrompt },',
  '      { role: "user", content: text },',
  '    ];',
  '',
  '    setStatus("🤔 AI 规划中...");',
  '    const result = await chrome.runtime.sendMessage({ action: "callAI", messages });',
  '    if (!result.success) {',
  '      addMessage("system", `❌ ${result.error}`);',
  '      setStatus("❌ 出错", "error");',
  '      return;',
  '    }',
  '',
  '    const aiText = result.text;',
  '',
  '    const toolRegex = /<TOOL>([\\s\\S]*?)<\\/TOOL>/g;',
  '    const tools = [];',
  '    let m;',
  '    while ((m = toolRegex.exec(aiText)) !== null) tools.push(m[1].trim());',
  '',
  '    if (tools.length === 0) {',
  '      addMessage("ai", aiText);',
  '      setStatus("✅ 完成", "");',
  '      return;',
  '    }',
  '',
  '    setStatus(`⏳ 执行 ${tools.length} 个步骤...`);',
  '    const images = [];',
  '    for (let i = 0; i < tools.length; i++) {',
  '      const toolCmd = tools[i];',
  '      setStatus(`⏳ (${i + 1}/${tools.length}) ${toolCmd.split("|")[0]}...`);',
  '      const r = await executeToolCommand(toolCmd);',
  '      if (r.imageUrl) images.push(r.imageUrl);',
  '    }',
  '',
  '    const displayText = aiText.replace(/<TOOL>[\\s\\S]*?<\\/TOOL>/g, "").trim();',
  '    if (displayText) addMessage("ai", displayText.replace(/\\n/g, "<br>"));',
  '',
  '    for (const imgUrl of images) {',
  '      const imgDiv = document.createElement("div");',
  '      imgDiv.innerHTML = `<img src="${imgUrl}" style="max-width:100%;border-radius:6px;margin:4px 0;box-shadow:0 2px 8px rgba(0,0,0,0.1)">`;',
  '      chatMessages.appendChild(imgDiv);',
  '      chatMessages.scrollTop = chatMessages.scrollHeight;',
  '    }',
  '',
  '    setStatus("✅ 完成", "");',
  '  } catch (err) {',
  '    addMessage("system", `❌ ${err.message}`);',
  '    setStatus("❌ 出错", "error");',
  '  } finally {',
  '    chatSend.disabled = false;',
  '  }',
  '}',
];

lines.splice(70, 30, ...replacement);
fs.writeFileSync(file, lines.join("\n"), "utf-8");
console.log("✅ Done");
